/** Downloads locally generated bytes without uploading workspace content. */
export function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  try {
    anchor.click();
  } finally {
    anchor.remove();
    // Leave enough time for browsers to start consuming large PDF/Word files.
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  }
}
